<?php
$devotion 		= $this->devotion4;
$devotion_prev	= $this->devotion_prev;
$devotion_next	= $this->devotion_next;
$recent_devotions	= $this->recent_devotions;
$this->headLink()->appendStylesheet($this->fullBaseUrl() .'/css/devotion.css');
$this->headLink()->appendStylesheet($this->fullBaseUrl() .'/css/sharrre.css');
$this->headScript()->appendFile(	'/js/jquery.sharrre.min.js' , 'text/javascript');
$this->headScript()->appendFile(	'/js/jquery.sharrre.js' , 'text/javascript');
//$this->headScript()->appendFile(	'http://static.ak.fbcdn.net/connect.php/js/FB.Share' , 'text/javascript');

if ($devotion)
{
$this->headMeta()->setProperty('og:title', $devotion['devotion_title']);
$this->headMeta()->setProperty('og:type', 'devotion, devotion');
$this->headMeta()->setProperty('og:description', substr(remove_html_tags($devotion['devotion_content']), 0, 200) . ' ...');

	/* Creating the Speaker Div */
//	$author_name 	= $devotion['devotion_author'] == '' ? $devotion['author_firstname']. ' ' . $devotion['author_lastname'] : $devotion['devotion_author'];
	
	$speaker_info	= $speaker_image = null;
	$date			= wrapHtml(	date('F ', 	strtotime($devotion['devotion_date'])), 'time', array('class'	=> 'month'));
	$date			.= wrapHtml(date('jS ', 	strtotime($devotion['devotion_date'])), 'time', array('class'	=> 'day'));
	$date			.= wrapHtml(date('Y ', 	strtotime($devotion['devotion_date'])), 'time', array('class'	=> 'year'));
	$date			.= ' '. wrapHtml(date('H:ia', strtotime($devotion['devotion_date'])), 'time', array('class'	=> 'time'));
	$date			= wrapHtml($date, 'date');
	$author_name_cont = wrapHtml(wrapHtml($author_name, 'span', array('class' => 'author-name')), 'a', array('class' => 'author-profile-link','href' => $devotion['devotion_author_view'], 'title'=>'View '.$author_name.'\'s profile')) ;
	$speaker_info	= wrapHtml(wrapHtml($author_name_cont. '<br />' . $date  , 'span',array('class' => 'author')),
														'td', array('class' 	=> 'ralign contentpad'));
	$speaker_image	= (!isset($devotion['speaker_image']) ? '' : 
	
									wrapHtml(wrapHtml('','img', array('src' 		=> $devotion['speaker_image'], 
									  					     'title'	=> $author_name, 
															 'width'	=> $devotion['speaker_image_w'], 
															 'height'	=> $devotion['speaker_image_h'],
															 'alt' 		=> 'image of ' . $author_name), true)
												, 'a', array('class' => 'author-profile-link','href' => $devotion['devotion_author_view'], 'title'=>'View '.$author_name.'\'s profile'))) ; 
	$speaker_image	= wrapHtml($speaker_image, 'td', array('class' => 'author')); /* Enclose inside td tags */
	$speaker_content= $speaker_info . $speaker_image;
	$speaker_table	= wrapHtml(wrapHtml($speaker_content, 'tr'),'table');
	$speaker_div	= wrapHtml($speaker_table, 'div', array('class' => 'speaker-info fr'));
	$speaker_div	.= wrapHtml('', 'div', array('class' => 'clr'));

}

?>
<?php if($devotion):?>
	<div id="devotion" class="contentpad mspacev fl">
		<div id="devotion-topic" class="">
			<header class="devotion-topic-head">
			<div id="devotion-title"><h2><?php echo $devotion['devotion_title'];?></h2>
			<?php echo $speaker_div;?>
			</header>
		</div>
		<?php if ($this->edit_link): ?>
		<p class="edit-devotion alignright nomargin"><a class="greenxbutton" href="<?php echo $this->edit_link;?>">Edit devotion</a></p>
		<?php endif;?>
		<div id="devotion-content" class="content">
		
		<?php echo $devotion['devotion_content'];
		
		/* Add Inset */
		$devotion_inset	= wrapHtml($devotion['devotion_highlight'], 'blockquote', array('class'=>'devotion-highlight'));
		echo $devotion_inset;
		?>
		</div>
		<div id="devotion-comment">
			<?php
				$comments	= array(); 
			?>
			<h3>Comments (<?php echo count($comments); ?>)</h3>
			<div id="devotion-comment-form" class="rdcorners contentpad lightgreybox">
			<div class="rdcorners contentpad whitebox">
				<p class="notice comment">There are no comments yet. Be the first to write and share your views.</p>
			</div>
			</div>
		</div>
	</div>
	<div id="sidepane" class="fl">
		<div id="devotion-tags" class="section">
		</div>
		<div id="share" class="section">
			<h3>Share This</h3>
			<div id="share-button-r" data-url="<?php echo $this->fullUrl;?>" data-text="<?php echo $devotion['devotion_title'];?>" data-title="share"></div>
			<script type="text/javascript">initSharrre('share-button-r');</script>
		</div>
		<div class="clr"></div>
		<div id="other-media" class="section">
			<div id="audio-section">
				<h3>Audio</h3>
				<p>Audio not available yet</p>
			</div>
			<div id="video-section">
				<h3>Video</h3>
				<p>video not available yet</p>
			</div>
		</div>
		<div id="devotion-calendar" class="section">
			<h3 class="recent-s">Recent Sermons</h3>
<!--
			<div class="greybox rdcorners contentpad devotion-nav"><?php //echo $devotion_prev ? $devotion_prev : 'None'; ?><span class="fr"><?php //echo $devotion_next ? $devotion_next : 'None'; ?></span></div> 
-->
			<div>
			<?php if ($recent_devotions):?>
			<table><?php foreach ($recent_devotions as $recent_devotion) 
			echo wrapHtml(
					wrapHtml(
						wrapHtml($recent_devotion['devotion_title'],'a', array(	'href' =>$recent_devotion['devotion_url'], 
																			'title' => $recent_devotion['devotion_highlight'])),
						'td', array('class'=>'recent')),
					'tr');?></table>
			<?php endif;?>
			<a href="<?php echo $this->fullUrl(array('action' =>'index'));?>" title="Go to devotions list" class="devotionlist rdcorners xbutton">All Sermons</a></div>
			<h4>Browse by calendar</h4>
			<?php echo $this->calendar;?>
		</div>
		
	</div>
	<div class="clr"></div>
<?php else:?>
	<div class="contentpad lightgreybox">
		<p>Check back soon</p>
	</div>
<?php endif;?>