<?php 
	$form 		= $this->form;
	//$article 	= $this->article;
	$this->headLink()->appendStylesheet($this->baseUrl() .'/css/articleedit.css');
	$this->headScript()->appendFile($this->baseUrl() .'/js/jquery.validate.js' , 'text/javascript');
	$this->headScript()->appendFile($this->baseUrl() .'/js/jquery.articleedit.js' , 'text/javascript');
?>
<div id="article-edit" class="">
	<?php if ($this->successmsg):?>
	<p id="successhead" class="headerfont info rdcorners greenbox"><strong>Done!</strong></p>
	<div class="info rdcorners whitebox">
		<p> <?php echo $this->successmsg; ?> </p>
	</div>
	<?php endif; ?>
	<?php if ($this->errormsgs){ echo '<div class="error rdcorners">'; foreach($this->errormsgs as $err) { echo '<p>'.$err.'</p>';} echo '</div>';}?>
	<?php if ($form):?>
		<div class="contentpad greybox rdcorners">
		<?php echo $form->getFormHeadTag(); ?>
		<div class="info whitebox rdcorners">
			<div class="form-field"><strong class="title">* Title:</strong><?php echo $form->title; ?></div>
			<div class="form-field"><strong class="title">Brief Description:</strong><?php echo $form->title_desc; ?></div>
			<div class="form-field"><strong class="title">*Aricle Content:</strong><div class="contentpad info"><?php echo $this->article_editor; ?></div></div>
			<div class="form-field"><strong class="title">*Tags</strong><?php echo $form->tags; ?></div>
			<div class="form-field"><strong class="title">&nbsp;</strong><?php echo $form->preview, ' &nbsp; ', $form->submit; ?></div>
		</div>
		<?php if($this->preview_article):?>
			<div class="info whitebox rdcorners">
			<h2 id="prev" class="aligncenter mspacev">Article Preview</h2>
			<div id="articles-preview" class="contentpad mspacev">
				<div id="article-topic-preview" class="">
					
					<header>
					<div id="article-title-preview" class="fl"><h2><?php echo $this->preview_title;?></h2>
					<?php if ($this->preview_author) echo '<p class="author">by <span class="aurthor-name">'.$this->preview_author .'</span><p>'; ?></div>
					<div id="article-date-preview" class="fl">
						<time class="month"><?php echo date('M', 	$this->preview_time); ?></time>
						<time class="day"><?php echo date('d', 		$this->preview_time); ?></time>
						<time class="year"><?php echo date('Y', 	$this->preview_time); ?></time>
						<div id="fb-root-preview"></div>
					</div>
					<div class="clr"></div>
					</header>
				</div>
				<div id="article-content-preview" class="content">
				
				<?php echo $this->preview_article;?>
				</div>
			</div>
			</div>
		<?php endif; ?>
		<?php echo $form->formClose(); ?>
		</div>	
	<?php else:?>
	<div class="info whitebox rdcorners">
		<p> Opps! Error</p>
	</div>
	<?php endif;?>
</div>