<?php
$baseUrl = Zend_Controller_Front::getInstance()->getRequest()->getHttpHost();
$url 	 = $this->url();
$news = $this->news;
$this->headLink()->appendStylesheet($this->baseUrl() .'/css/news.css');
//$this->headLink()->appendStylesheet($this->baseUrl() .'/css/sharrre.css');
//$this->headScript()->appendFile(	'/js/jquery.sharrre.min.js' , 'text/javascript');
//$this->headScript()->appendFile(	'/js/jquery.sharrre.js' , 'text/javascript');
//$this->headScript()->appendFile(	'http://static.ak.fbcdn.net/connect.php/js/FB.Share' , 'text/javascript');

if ($news)
{
$this->headMeta()->setProperty('og:title', $news['news_title']);
$this->headMeta()->setProperty('og:type', 'news');
//$this->headMeta()->setProperty('og:description', 'description');
}
?>
<?php if($news):?>
	<div id="news" class="contentpad mspacev fl">
		<div id="news-topic" class="">
			<header>
			<div id="news-title" class="fl"><h2><?php echo $news['news_title'];?></h2>
			<?php // if ($this->author) echo '<p class="author">by <span class="aurthor-name">'.$this->author .'</span><p>'; ?></div>
<!--
			<div id="news-date" class="fl">
				<time class="month"><?php echo date('M', strtotime($news['news_date'])); ?></time>
				<time class="day"><?php echo date('d', strtotime($news['news_date'])); ?></time>
				<time class="year"><?php echo date('Y', strtotime($news['news_date'])); ?></time>
			</div>
-->
			<div class="clr"></div>
			</header>
		</div>
		<?php if ($this->edit_link): ?>
		<p class="alignright nomargin"><a class="greenxbutton" href="<?php echo $this->edit_link;?>">Edit News</a></p>
		<?php endif;?>
		<div id="news-content" class="content">
		
		<?php echo $news['news_content'];?>
		</div>
	</div>
	<div id="sidepane" class="fl">
		<div id="news-tags" class="section">
			<h3>Tags</h3>
			<p><i><?php echo $news['news_tags'];?></i></p>
		</div>
	</div>
	<div class="clr"></div>
<?php else:?>
	<div class="contentpad lightgreybox">
		<h3>Oops.. Error Fetching News.</h3>
		<p>We are sorry, it appears this page can not be found.</p>
		<p>It might require you to have the necessary prividges</p>
	</div>
<?php endif;?>