<?php
$baseUrl = Zend_Controller_Front::getInstance()->getRequest()->getHttpHost();
$form 	= $this->form;
$sermon = $this->sermon;
$this->headLink()->appendStylesheet($this->fullBaseUrl() .'/css/sermonremove.css');
?>
<div id="sermon" class="contentpad info">
<?php if($form):?>
	<div class="form">
		<p class="confirm-clause">Are you sure you want to remove <strong><em><?php echo wrapHtml($sermon['sermon_title'], 'a', array('href' => $sermon['sermon_url'], 'title' => $sermon['sermon_highlight']));?></em></strong><br /></p>
		<?php echo $form->getFormHeadTag();?>
		<div><span class="buttoncont"><?php echo $form->cancel;?></span><span class="buttoncont"><?php echo $form->remove;?></span></div>
		<?php echo $form->s_id;?>		
		</form>
	</div>
<?php else:?>
<?php if ($this->successmsg):?>
<p id="successhead" class="headerfont info rdcorners greenbox"><strong>Done!</strong></p>
<div class="info rdcorners whitebox">
	<p> <?php echo $this->successmsg; ?> </p><p>Go <?php echo wrapHtml('Back', 'a', array('class'=> 'xbutton', 'href'=> $this->url(array('action'=>'index'), false, null))); ?> to all sermons.</p>
</div>
<?php else: ?>
<div class="contentpad lightgreybox">
		<h3>Oops.. Error Fetching Sermon.</h3>
		<p>Please select a sermon to remove</p>
	</div>
<?php endif; ?>
	
<?php endif;?>
</div>