<?php
$baseUrl = Zend_Controller_Front::getInstance()->getRequest()->getHttpHost();
$form 	= $this->form;
$news = $this->news;
$this->headLink()->appendStylesheet($this->baseUrl() .'/css/articleremove.css');
//$this->headLink()->appendStylesheet($this->baseUrl() .'/css/sharrre.css');
//$this->headScript()->appendFile(	'/js/jquery.sharrre-1.2.0.min.js' , 'text/javascript');
//$this->headScript()->appendFile(	'/js/jquery.sharrre.js' , 'text/javascript');
//$this->headScript()->appendFile(	'http://static.ak.fbcdn.net/connect.php/js/FB.Share' , 'text/javascript');
?>
<div id="news" class="contentpad info">
<?php if($form):?>
	<div class="form">
		<p class="confirm-clause">Are you sure you want to remove <strong><em><?php echo wrapHtml($news['news_title'], 'a', array('href' => $news['news_url'], 'title' => $news['news_desc']));?></em></strong><br /></p>
		<?php echo $form->getFormHeadTag();?>
		<div><span class="buttoncont"><?php echo $form->cancel;?></span><span class="buttoncont"><?php echo $form->remove;?></span></div>
		<?php echo $form->n_id;?>		
		</form>
	</div>
<?php else:?>
<?php if ($this->successmsg):?>
<p id="successhead" class="headerfont info rdcorners greenbox"><strong>Done!</strong></p>
<div class="info rdcorners whitebox">
	<p> <?php echo $this->successmsg; ?> </p><p><strong>Go <?php echo wrapHtml('Back', 'a', array('class'=> 'xbutton', 'href'=> $this->url(array('action'=>'allnews'), false, null))); ?> to all news.</strong></p>
</div>
<?php else: ?>
<div class="contentpad lightgreybox">
		<h3>Oops.. Error Fetching News.</h3>
		<p>Please select a news to remove</p>
	</div>
<?php endif; ?>
	
<?php endif;?>
</div>