<div id="user-profile">
<?php
	//$script = "\$(function(){	var b = \$('#changepassword'); b.click(function(){\$('#passwordtable').toggle(400,'linear',function(){ if (b.text()=='Change Password') b.text('Hide'); else b.text('Change Password');});});});";
	//$this->headScript()->appendScript($script, $type = 'text/javascript');
	$form = $this->form;
	$user = $this->user;
	$this->headLink()->appendStylesheet($this->baseUrl() .'/css/profile.css');
	$this->headLink()->appendStylesheet($this->baseUrl() .'/css/edituser.css');
	$this->headScript()->appendFile($this->baseUrl() .'/js/jquery.validate.js' , 'text/javascript');
	$this->headScript()->appendFile($this->baseUrl() .'/js/jquery.edituser.js' , 'text/javascript');
	
	$baseUrl = $this->baseUrl() . '/';
	
?>
	<?php if ($this->successmsg):?>
	<p id="successhead" class="headerfont info rdcorners greenbox"><strong><?php echo $this->successmsg;?></strong></p>
	<?php endif; ?>
		<?php if ($this->errors){ echo '<div class="info rdcorners whitebox ajustify"><div class="error rdcorners">'; foreach($this->errors as $err) { echo '<p>'.$err.'</p>';} echo '</div></div>';}?>
	<div class="rdcorners contentpad">
		<div class="fl lsidebar maxheight">
			<div class="lightgreybox rdcorners contentpad mspacev">
				<p class="whitebox contentpad centeralign">
					<img src="<?php echo $baseUrl . APP_PROFILE_IMAGES_DIRECTORY . $user['user_profile_image'];?>" width="154" height="160" title="Profile Pix" /></p>
				<a href="">Change image</a>
			</div>
			<div class="lightgreybox rdcorners contentpad mspacev mspacev">
				Tools
			</div>
		</div>
		<div class="fl subcontent">
		<?php if($form): echo $form->getFormHeadTag();?>
			<div class="greybox rdcorners contentpad mspaceall profile">
				<table  class="mdlalign"><tbody>
					<?php 
						echo $form->firstname->setValue($user['user_fname']);
						echo $form->lastname->setValue($user['user_lname']);
						echo $form->email->setValue($user['email']);
						echo '<tr><td width="35%"><label for="birthday">* Password: </label></td><td><button id="changepassword" class="button" onclick="return true;">Change Password</button></td></tr>';
					?>
				</tbody></table>
				<table id="passwordtable" class="mdlalign"><tbody>
					<?php 
						echo $form->oldpassword;
						echo $form->password;
						echo $form->password2;
					?>
				</tbody></table>
			</div>
			<br />
			<div class="greybox rdcorners contentpad mspaceall profile">
				<table  class="mdlalign"><tbody>
					<?php 
						$gender = ($user['user_gender'] == 'male' ? 1 : 2);
						$d		= date('j', strtotime($user['user_date_of_birth']));
						$m		= date('n', strtotime($user['user_date_of_birth']));
						$y		= date('Y', strtotime($user['user_date_of_birth']));
						
						echo '<tr><td width="35%"><label for="birthday">* Gender: </label></td><td>', $form->gender->setValue($gender), '</td></tr>';
						echo '<tr><td width="35%"><label for="birthday">* Date of Birth: </label></td><td>', $form->day->setValue($d), $form->month->setValue($m), $form->year->setValue($y), '<div id="dateerror"></div></td></tr>';
						echo $form->mobile->setValue($user['user_mobile']);				
						echo $form->address1->setValue($user['user_address']);
						echo $form->address2->setValue($user['user_address2']);
						echo $form->town->setValue($user['user_town']);
						echo $form->zip->setValue($user['user_zip']);
						echo $form->state->setValue($user['state_id']);
						echo $form->country->setValue($user['country_id']);
						echo $form->hidden1;
						echo $form->submit->setLabel(' Update ');
					?>
				</tbody></table>
			</div>
			<?php if (!empty($form)) echo $form->formClose(); endif; ?>
		</div>
		<div class="clr"></div>
	</div>
</div>