<?php 
	$form = $this->form;
	$successmsg = $this->successmsg;
	$errormsg = $this->errormsg;
	$this->headLink()->appendStylesheet($this->baseUrl() .'/css/resetpassword.css');
	$this->headScript()->appendFile($this->baseUrl() .'/js/jquery.validate.js' , 'text/javascript');
	$this->headScript()->appendFile($this->baseUrl() .'/js/jquery.registration.js' , 'text/javascript');
?>
<div id="wrapper">
<?php if ($successmsg):?>
	<p id="successhead" class="headerfont info rdcorners greenbox"><strong>Change Password</strong></p>
	<div class="info rdcorners whitebox">
		<p> <?php echo $successmsg; ?> </p>
	</div>
	<?php elseif ($errormsg): ?>

	<p id="successhead" class="headerfont info rdcorners milderror"><strong>Something went wrong!</strong></p>
	<div class="info rdcorners lightgreybox">
		<p> <?php echo $errormsg; ?> </p>
	</div>
	<?php endif; ?>
	<?php if ($this->errors){ echo '<div class="error rdcorners">'; foreach($this->errors as $err) { echo '<p>'.$err.'</p>';} echo '</div>';}?>
	
	<?php if (!$successmsg):?>
	<div class="rdcorners info lightgreybox" id="reset-password-page">
	<table  class="mdlalign"><tbody>
	<?php echo $form->getFormHeadTag();?>
	<?php echo $form->oldpassword;?>
	<?php echo $form->password;?>
	<?php echo $form->password2;?>
	<tr><td>&nbsp;</td><td><?php echo $form->submit;?></td></tr>
	<?php echo $form->code;?>
	<?php echo $form->hash;?>
	<?php echo $form->getCloseTag(); ?>
	</tbody></table>
	</div>
	<?php endif;?>
	
</div>
