<div class="lightgreybox">
<div id="main" class="fl whitebox">
	<div class="m_cont">
		{{%hypertext:content1%}}		 
	</div>
	<div class="m_cont">
		<div id="sub1" class="fl">
			<h3>News Updates</h3>
			<div class="m_cont">
				{{%hypertext:news1%}}
			</div>
		</div><!-- end sub1 -->
		<div id="sub2" class="fl">
			<div class="m_cont">
				{{%hypertext:wordquote1%}}
			</div>
			<div class="m_cont">
				{{%hypertext:others%}} 
				<div class="hrbr">&nbsp;</div>
			</div>
			<div id="sbpryr">
				{{%form:prayer%}}
				<div class="hrbr">&nbsp;</div>
			</div>
		</div><!-- end sub2 -->
		<div class="clr"></div>
	</div>
</div><!-- End of main -->
<div id="s2" class="fl">
	{{%slider:picture1%}}
	<div id="ss2" class="fle">
		<div class="m_cont">
			<h3>Events</h3>
			{{%events:calendar%}}
			<!-- <img src="/images/te2.jpg" alt="pstr" title="Pastor Pung &amp; Mr Joshua" align="left" /> -->
		</div><!-- end events -->
		
		<div class="m_cont">
			{{%hypertext:community%}} 
		</div>
		
	</div>
</div><!-- End s2 -->
<div class="clr"></div>
</div>