<?php 
	$form 		= $this->form;
	$article 	= $this->article;
	$this->headLink()->appendStylesheet($this->baseUrl() .'/css/imageupload.css');
	$this->headScript()->appendFile($this->baseUrl() .'/js/jquery.validate.js' , 'text/javascript');
	$this->headScript()->appendFile($this->baseUrl() .'/js/jquery.imageupload.js' , 'text/javascript');
?>
<div id="article-edit" class="contentpad greybox rdcorners">
	<?php if ($this->successmsg):?>
	<p id="successhead" class="headerfont info rdcorners greenbox"><strong>Done!</strong></p>
	<div class="info rdcorners whitebox">
		<p> <?php echo $this->successmsg; ?> </p>
	</div>
	<?php endif; ?>
	<?php if ($this->errormsgs){ echo '<div class="error rdcorners">'; foreach($this->errormsgs as $err) { echo '<p>'.$err.'</p>';} echo '</div>';}?>
	<?php if ($form):?>
		<div>
		<?php echo $form->getFormHeadTag(); ?>
		<div class="info whitebox rdcorners">
			<div class="form-field"><strong class="title">* Album:</strong><?php echo $form->image_album; ?></div>
			<div class="form-field"><strong class="title">* Filename:</strong><?php echo $form->image_upload1; ?><p class="mspacev"><strong class="title">Brief Description:</strong><?php echo $form->image_desc1; ?></p></div>
			<div class="form-field"><strong class="title"> Filename:</strong><?php echo $form->image_upload2; ?><p class="mspacev"><strong class="title">Brief Description:</strong><?php echo $form->image_desc2; ?></p></div>
			<div class="form-field"><strong class="title"> Filename:</strong><?php echo $form->image_upload3; ?><p class="mspacev"><strong class="title">Brief Description:</strong><?php echo $form->image_desc3; ?></p></div>
			<div class="form-field"><strong class="title">&nbsp;</strong><?php echo $form->submit; ?></div>
		</div>
		<?php echo $form->formClose(); ?>
		</div>	
	<?php else:?>
	<div class="info whitebox rdcorners">
		<p> Opps! Error</p>
	</div>
	<?php endif;?>
</div>