<div id="tabs<?= $this->id;?>" class="tabsholder">
	<ul class="xtabs">
		<li><a href="#tabs-1">Tab 1</a></li>
		<li><a href="#tabs-2">Tab 2</a></li>
		<li><a href="#tabs-3">Tab 3</a></li>
	</ul>
	<div class="tab_container">
		<div id="tabs-1"  class="tab_content">
			<p>My Content 1</p>
		</div>
		<div id="tabs-2"  class="tab_content">
			<p>MY content 2</p>
		</div>
		<div id="tabs-3" class="tab_content">
			<p>Content 3</p>
		</div>
	</div><!-- tabs_container -->
</div>