<div class="h-all">
<div id="topslider" class="autohide">{{%imageSlider:picture1%}}</div>
<div id="main" class="fl">
	<div class="m_cont">
		{{%sermons:content1%}}		 
	</div>
	<div class="m_cont">
		<div class="m_cont">
			{{%articles:writeup%}}
		</div>
		<div class="m_cont">
			{{%discussion:wordquote1%}}
		</div>
	</div>
</div><!-- End of main -->
<div id="s2" class="fl">
	<div id="ss2" class="fle">
		<div class="m_cont">
			{{%news:community%}} 
		</div><!-- end news -->
		<div class="m_cont">
			{{%events:calendar%}}
		</div><!-- end events -->
		<div class="m_cont">
			 
		</div><!-- end picture slider -->		
	</div>
</div><!-- End s2 -->
<div class="clr"></div>
</div>