<?php $script = "\$(function(){	var b = \$('#showmap'); b.click(function(){\$('#map').toggle(400,'linear',function(){ if (b.text()=='Hide') b.text('Show'); else b.text('Hide');});});});";
	$this->headScript()->appendScript($script, $type = 'text/javascript');
?>
<div id="topic">				
	<div class="info contentpad greybox rdcorners">
		<h2 class="contentpad info" style="height:2.5em;">Location Map <span class="fr"><button id="showmap" class="togglebutton">Hide</button></span><span class="clr"></span><br /></h2>
		<div id="map" class="whitebox rdcorners contentpad aligncenter info">
		<p class="lightgrey info contentpad"><strong class="rdcorners contentpad greenbox">You can locate us at:</strong></p>
		<p class="aligncenter">
			<b><span class="redtitle"><?php echo APP_CHURCH_NAME;?></span></b><br /><br />
			19, Jalan OP 1/1, Pusat Perdagangan One Puchong<br />
			Off LDP, 47160 Puchong, Selangor<br />
			Tel: +603-8075-8784<br />
			Email: permaicmc@yahoo.com
		</p>
		<p><iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=one+puchong,+puchong+selangor,+malaysia&amp;aq=&amp;sll=37.0625,-95.677068&amp;sspn=37.273371,56.513672&amp;vpsrc=6&amp;ie=UTF8&amp;hq=one+puchong,&amp;hnear=Puchong,+Selangor,+Malaysia&amp;t=m&amp;ll=3.040154,101.618514&amp;spn=0.010971,0.013797&amp;z=14&amp;iwloc=A&amp;cid=12829378705176025492&amp;output=embed"></iframe><br /><small><a href="http://maps.google.com/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=one+puchong,+puchong+selangor,+malaysia&amp;aq=&amp;sll=37.0625,-95.677068&amp;sspn=37.273371,56.513672&amp;vpsrc=6&amp;ie=UTF8&amp;hq=one+puchong,&amp;hnear=Puchong,+Selangor,+Malaysia&amp;t=m&amp;ll=3.040154,101.618514&amp;spn=0.010971,0.013797&amp;z=14&amp;iwloc=A&amp;cid=12829378705176025492" style="color:#0000FF;text-align:left">View Larger Map</a></small></p>
		</div>
		<div id="map" class="whitebox rdcorners contentpad aligncenter info">d</div>
	</div>