<?php 
	/**
	* ============================================
	*	Initial Configs and necessary headers...
	* ============================================
	*/
	$baseUrl = $this->baseUrl() . DIRECTORY_SEPARATOR;
?><div id="main" class="fl">
	<div class="m_cont">
		<h2>About <?= trim($this->getAppConfig()->mainName); ?></h2>
		<h3>Brief Introduction</h3>
		<p>
		 <strong>Permai Chinese Methodist Church (PCMC)</strong> was originally a ministry of the 
		 <i>Chin Hock Chinese Methodist Church</i> of Manjung District.
		</p> 
		<p>Back then, a group of young believers from Manjung District left their hometown for the Klang Valley to pursue their studies and careers. Away from home, they formed a fellowship called Chin Hock Kuala Lumpur Fellowship to provide mutual support for each other. In 1999, the fellowship was turned into a Preaching Point.
		</p>
		<h3>Our Ministries</h3>
		<p>
		 <strong>Permai Chinese Methodist Church</strong> is dedicated to the following ministries...
		</p> 
		<ul>
			<li>Children Sunday School</li>
			<li>Weekly Prayer Meeting and Bible Study Class</li>
			<li>Care Group Ministry</li>
			<li>Youth Ministry</li>
			<li>Senior Citizen Ministry,</li> 
			<li>Table Fellowship, </li>
			<li>Literature Ministry</li>
			<li>Library, Social Concern Ministry. </li>
			<li>Overseas mission: Cambodia, the Philippines and Thailand.</li>
		</ul>
	</div>
	
</div><!-- End of main -->
<div id="s2" class="fl">
	<div id="events"></div>
		<h3>Contact Us</h3>
		<div class="m_cont">
			<table cellspacing="0" cellpadding="0" border="0">
				<tr>
					<td>
						<iframe 
						src="http://maps.google.com.my/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=Permai+Chinese+Methodist+CHURCH+%E8%92%B2%E7%A7%8D+Selangor&amp;aq=2&amp;oq=permai+c&amp;sll=4.109495,109.101269&amp;sspn=25.302765,43.286133&amp;ie=UTF8&amp;hq=Permai+Chinese+Methodist+Church+%E8%92%B2%E7%A7%8D+Selangor&amp;hnear=&amp;t=m&amp;ll=3.03994,101.618921&amp;spn=0.002925,0.005284&amp;z=16&amp;iwloc=A&amp;cid=7069347760790555860&amp;output=embed" Style="width: 100%;" height="400" marginwidth="0" marginheight="0" frameborder="0" scrolling="no">
						</iframe>
					</td>
				</tr>
			</table>
		</div>
	</div>
</div><!-- end about -->
</div><!-- End s2 -->

<div class="clr"></div>