<?php 
	/**
	* ============================================
	*	Initial Configs and necessary headers...
	* ============================================
	*/
	$baseUrl = $this->baseUrl() . DIRECTORY_SEPARATOR;
?><div id="main" class="fl">
	<div class="m_cont">
		<h2>Events Details</h2>
		<h3>Week 33 (August 14th - 20th)</h3>
		<ul>
			<li>We going to Cambodia for outreach</li>
			<li>Choir Rehearsals</li>
		<li>
			
	</div>
	
</div><!-- End of main -->
<div id="s2" class="fl">
	<div id="events"></div>
		<h3>Events Calendar</h3>
			<div class="m_cont">
				<table style="margin: 0 auto; border:1px solid #555; text-align: center; border-collapse: separate;" border="0" width="90%"> 
<tr style="background-color: #eee;"> 
<th width="12%">Wk</th> 
<th width="12%">Su</th> 
<th width="12%">M</th> 
<th width="12%">Tu</th> 
<th width="12%">W</th> 
<th width="12%">Th</th> 
<th width="12%">F</th> 
<th width="12%">Sa</th> 
</tr> 
<tr style="background-color:#fff;"> 
<td style="background-color:#fed;"  onmouseover="style.backgroundColor='#9ff'"; onmouseout="style.backgroundColor='#fed'";><b>22</b></td> 
<td >&nbsp;</td> 
<td >&nbsp;</td> 
<td >&nbsp;</td> 
<td style="background-color:#fff;"  onmouseover="style.backgroundColor='#9f9'"; onmouseout="style.backgroundColor='#fff'";>1</td> 
<td style="background-color:#fff;"  onmouseover="style.backgroundColor='#9f9'"; onmouseout="style.backgroundColor='#fff'";>2</td> 
<td style="background-color:#fff;"  onmouseover="style.backgroundColor='#9f9'"; onmouseout="style.backgroundColor='#fff'";>3</td> 
<td style="background-color:#fff;"  onmouseover="style.backgroundColor='#9f9'"; onmouseout="style.backgroundColor='#fff'";>4</td> 
</tr> 
<tr style="background-color:#fff;"> 
<td style="background-color:#fed;"  onmouseover="style.backgroundColor='#9ff'"; onmouseout="style.backgroundColor='#fed'";><b>23</b></td> 
<td style="background-color:#fff;"  onmouseover="style.backgroundColor='#9f9'"; onmouseout="style.backgroundColor='#fff'";>5</td> 
<td style="background-color:#fff;"  onmouseover="style.backgroundColor='#9f9'"; onmouseout="style.backgroundColor='#fff'";>6</td> 
<td style="background-color:#fff;"  onmouseover="style.backgroundColor='#9f9'"; onmouseout="style.backgroundColor='#fff'";>7</td> 
<td style="background-color:#fff;"  onmouseover="style.backgroundColor='#9f9'"; onmouseout="style.backgroundColor='#fff'";>8</td> 
<td style="background-color:#fff;"  onmouseover="style.backgroundColor='#9f9'"; onmouseout="style.backgroundColor='#fff'";>9</td> 
<td style="background-color:#fff;"  onmouseover="style.backgroundColor='#9f9'"; onmouseout="style.backgroundColor='#fff'";>10</td> 
<td style="background-color:#fff;"  onmouseover="style.backgroundColor='#9f9'"; onmouseout="style.backgroundColor='#fff'";>11</td> 
</tr> 
<tr style="background-color:#fff;"> 
<td style="background-color:#fed;"  onmouseover="style.backgroundColor='#9ff'"; onmouseout="style.backgroundColor='#fed'";><b>24</b></td> 
<td style="background-color:#fff;"  onmouseover="style.backgroundColor='#9f9'"; onmouseout="style.backgroundColor='#fff'";>12</td> 
<td style="background-color:#fff;"  onmouseover="style.backgroundColor='#9f9'"; onmouseout="style.backgroundColor='#fff'";>13</td> 
<td style="background-color:#fff;"  onmouseover="style.backgroundColor='#9f9'"; onmouseout="style.backgroundColor='#fff'";>14</td> 
<td style="background-color:#fff;"  onmouseover="style.backgroundColor='#9f9'"; onmouseout="style.backgroundColor='#fff'";>15</td> 
<td style="background-color:#fff;"  onmouseover="style.backgroundColor='#9f9'"; onmouseout="style.backgroundColor='#fff'";>16</td> 
<td style="background-color:#fff;"  onmouseover="style.backgroundColor='#9f9'"; onmouseout="style.backgroundColor='#fff'";>17</td> 
<td style="background-color:#fff;"  onmouseover="style.backgroundColor='#9f9'"; onmouseout="style.backgroundColor='#fff'";>18</td> 
</tr> 
<tr style="background-color:#fff;"> 
<td style="background-color:#fed;"  onmouseover="style.backgroundColor='#9ff'"; onmouseout="style.backgroundColor='#fed'";><b>25</b></td> 
<td style="background-color:#fff;"  onmouseover="style.backgroundColor='#9f9'"; onmouseout="style.backgroundColor='#fff'";>19</td> 
<td style="background-color:#fff;"  onmouseover="style.backgroundColor='#9f9'"; onmouseout="style.backgroundColor='#fff'";>20</td> 
<td style="background-color:#fff;"  onmouseover="style.backgroundColor='#9f9'"; onmouseout="style.backgroundColor='#fff'";>21</td> 
<td style="background-color:#fff;"  onmouseover="style.backgroundColor='#9f9'"; onmouseout="style.backgroundColor='#fff'";>22</td> 
<td style="background-color:#fff;"  onmouseover="style.backgroundColor='#9f9'"; onmouseout="style.backgroundColor='#fff'";>23</td> 
<td style="background-color:#fff;"  onmouseover="style.backgroundColor='#9f9'"; onmouseout="style.backgroundColor='#fff'";>24</td> 
<td style="background-color:#fff;"  onmouseover="style.backgroundColor='#9f9'"; onmouseout="style.backgroundColor='#fff'";>25</td> 
</tr> 
<tr style="background-color:#fff;"> 
<td style="background-color:#fed;"  onmouseover="style.backgroundColor='#9ff'"; onmouseout="style.backgroundColor='#fed'";><b>26</b></td> 
<td style="background-color:#fff;"  onmouseover="style.backgroundColor='#9f9'"; onmouseout="style.backgroundColor='#fff'";>26</td> 
<td style="background-color:#fff;"  onmouseover="style.backgroundColor='#9f9'"; onmouseout="style.backgroundColor='#fff'";>27</td> 
<td style="background-color:#fff;"  onmouseover="style.backgroundColor='#9f9'"; onmouseout="style.backgroundColor='#fff'";>28</td> 
<td style="background-color:#fff;"  onmouseover="style.backgroundColor='#9f9'"; onmouseout="style.backgroundColor='#fff'";>29</td> 
<td style="background-color:#fff;"  onmouseover="style.backgroundColor='#9f9'"; onmouseout="style.backgroundColor='#fff'";>30</td> 
<td >&nbsp;</td> 
<td >&nbsp;</td> 
</tr> 
</table></div>
	</div>
</div><!-- end events -->
</div><!-- End s2 -->

<div class="clr"></div>

