		<div id="hdr">
				<div id="c_lg" class="fl">
					<a href="{$$APP_HOMEURL}">
						<img src="/images/pcmc_lg.png" alt="Church Logo" title="{$CHURCH_NAME} ChurchPoint&trade;" />
					</a>
				</div><div class="clr"></div>
				<div id="hdr_in" class="ctrpg">
					<div id="lg" class="fl nldcr">
						<a alt="Logo" href="#" title="Church Logo"><span class="altname">{$CHURCH_ALTERNATE_NAME}基督教卫理公会百美堂</span>
						{$CHURCH_NAME}Permai Chinese Methodist Church
						<small>{$CHURCH_SLOGAN}Winning daily prayerful through His Word!</small></a>
					</div>
					<div id="usr" class="fr">
						<div id="cplg">ChurchPoint<small>&trade;</small></div>
						<div>You are viewing as 
							<span class="nldcr unm">[<a href="#" alt="Kheng Lee" title="View Profile">Kheng Lee</a>]
							[<a href="#" alt="Logout" title="Sign out of ChurchPoint&trade;">Logout</a>]</span>
						</div>
					</div>
					<div class="clr"></div>
				</div>
			</div><!-- end hdr -->